apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtub2e-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: youtub2e
  template:
    metadata:
      labels:
        app: youtub2e
    spec:
      containers:
      - name: youtub2e
        image: sevenajay/youtube:1.0.33
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: youtub2e-service
spec:
  selector:
    app: youtub2e
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer  # Change to NodePort or ClusterIP based on your requirements
