apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: youtube
  template:
    metadata:
      labels:
        app: youtube
    spec:
      containers:
      - name: youtube
        image: murulii/youtube:1.0.22
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: youtube-service
spec:
  selector:
    app: youtube
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer  # Change to NodePort or ClusterIP based on your requirements
